[[badge]]
filename = "left/_rss.gif"
url = "/rss.xml"
order = 0

[[badge]]
filename = "left/_css-is-difficult.gif"
url = "https://www.w3.org/Style/CSS/current-work"
order = 1

[[badge]]
filename = "left/_eliminate-drm-now.png"
url = "https://www.defectivebydesign.org/action"
order = 2

[[badge]]
filename = "left/_iso-dates.png"
url = "https://www.w3.org/QA/Tips/iso-date"
order = 3

[[badge]]
filename = "left_ext/howlongmojang.gif"
url = "https://marshdeer.github.io/howlongmojang/"
order = 0

[[badge]]
filename = "right/bluesky.png"
url = "https://bsky.app/profile/lunnova.dev"
order = 0
title = "@lunnova.dev on bsky.app"

[[badge]]
filename = "self/lunnova.dev.png"
url = "https://lunnova.dev/#b_lunnova"
order = 1
title = "feeling a little loopy!"
